import { combineReducers } from "redux";
import {
  gethompageReducers,
  getcountrynameReducers,
  getStatenameReducers,
  getcitynmaeReducers,
  getcategorylistReducers,
  getvalidservicecategoryReducers,
  getserviceReducers,
  getuserprofiledetailsReducers,
  getservicedetailsReducers,
  getwishlistReducers,
  anotherservicefromsamesellerReducers,
  getrecommendedserviceReducers,
  getlocalstoragedataReducers,
  gettocartReducers,
  userProfileEditReducers,
  userconversationnameReducers,
  userconversationdetailsReducers,
  userconverstionlistReducers,
  getreviewlistReducers,
} from "./reducers";
export const rootReducer = combineReducers({
  gethompageReducers: gethompageReducers,
  getcountrynameReducers: getcountrynameReducers,
  getStatenameReducers: getStatenameReducers,
  getcitynmaeReducers: getcitynmaeReducers,
  getcategorylistReducers: getcategorylistReducers,
  getvalidservicecategoryReducers: getvalidservicecategoryReducers,
  getserviceReducers: getserviceReducers,
  getuserprofiledetailsReducers: getuserprofiledetailsReducers,
  getservicedetailsReducers: getservicedetailsReducers,
  getwishlistReducers: getwishlistReducers,
  anotherservicefromsamesellerReducers: anotherservicefromsamesellerReducers,
  getrecommendedserviceReducers: getrecommendedserviceReducers,
  getlocalstoragedataReducers: getlocalstoragedataReducers,
  gettocartReducers: gettocartReducers,
  userProfileEditReducers: userProfileEditReducers,
  userconversationnameReducers: userconversationnameReducers,
  userconversationdetailsReducers: userconversationdetailsReducers,
  userconverstionlistReducers: userconverstionlistReducers,
  getreviewlistReducers: getreviewlistReducers,
});
